# Site settings
title: The Best Site Ever
email: danieswain@gmail.com
description: >
  Daniel Swain Jr's (lumizze) github web page.
baseurl: "/blog" 
url: "http://lumizze.github.io"
twitter_username: danieswain
github_username:  lumizze

# Build settings
markdown: kramdown
permalink: /:year/:title:output_ext